apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: backend
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: openhackteam2acr.azurecr.io/tripinsights/trips:1.0
        envFrom:
          - secretRef:
              name: dbconnectionstring
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80